package com.example.patent.common;

import com.example.patent.service.OpenAiService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * Three-layer SQL safety validator:
 *   Layer 1 — static rule checks (read-only, no DDL/DML, LIMIT enforced)
 *   Layer 2 — EXPLAIN syntax validation
 *   Layer 3 — AI self-check with auto-retry
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class SqlValidator {

    private static final int MAX_ROWS = 500;
    private static final int MAX_RETRY = 2;

    private static final Set<String> BLOCKED_KEYWORDS = Set.of(
            "DROP ", "DELETE ", "UPDATE ", "INSERT ", "ALTER ", "TRUNCATE ", "CREATE ",
            "REPLACE ", "GRANT ", "REVOKE ", "EXEC ", "CALL "
    );

    private static final Set<String> BLOCKED_SCHEMAS = Set.of(
            "information_schema", "mysql", "performance_schema", "sys"
    );

    private static final Pattern SELECT_PATTERN = Pattern.compile(
            "^\\s*(SELECT|WITH)\\s", Pattern.CASE_INSENSITIVE
    );

    private static final Pattern HAS_LIMIT = Pattern.compile(
            "LIMIT\\s+\\d+", Pattern.CASE_INSENSITIVE
    );

    private static final Pattern BLOCKED_SCHEMA_PATTERN = Pattern.compile(
            "(FROM|JOIN|INTO)\\s+(information_schema|mysql|performance_schema|sys)\\.",
            Pattern.CASE_INSENSITIVE
    );

    private final JdbcTemplate jdbcTemplate;
    private final OpenAiService openAiService;

    /**
     * Validate an AI-generated SQL query. Returns the validated SQL with LIMIT appended.
     *
     * @param rawSql the SQL generated by AI
     * @return validated SQL string
     * @throws SqlValidationException if validation fails after retries
     */
    public ValidatedSql validate(String rawSql) throws SqlValidationException {
        return validate(rawSql, 0);
    }

    private ValidatedSql validate(String sql, int retryCount) throws SqlValidationException {
        // Layer 1: static rules
        String cleaned = sql.trim();

        // Remove markdown code blocks if present
        if (cleaned.startsWith("```")) {
            int start = cleaned.indexOf('\n') + 1;
            int end = cleaned.lastIndexOf("```");
            if (end > start) {
                cleaned = cleaned.substring(start, end).trim();
            }
        }

        // Must be SELECT or WITH
        if (!SELECT_PATTERN.matcher(cleaned).find()) {
            throw new SqlValidationException("只允许 SELECT 查询", cleaned);
        }

        // Block dangerous keywords
        String upper = cleaned.toUpperCase(Locale.ROOT);
        for (String kw : BLOCKED_KEYWORDS) {
            if (upper.contains(kw)) {
                throw new SqlValidationException("禁止的危险操作: " + kw.trim(), cleaned);
            }
        }

        // Block system schemas
        if (BLOCKED_SCHEMA_PATTERN.matcher(cleaned).find()) {
            throw new SqlValidationException("禁止查询系统库表", cleaned);
        }

        // Layer 2: EXPLAIN syntax check
        try {
            jdbcTemplate.queryForList("EXPLAIN " + cleaned);
        } catch (Exception e) {
            String errorMsg = e.getMessage();
            log.warn("SQL 语法校验失败: {}", errorMsg);

            if (retryCount < MAX_RETRY) {
                // Layer 3: AI self-correct
                String corrected = askAiToFix(cleaned, errorMsg);
                return validate(corrected, retryCount + 1);
            }
            throw new SqlValidationException("SQL 语法错误: " + errorMsg, cleaned);
        }

        // Append LIMIT if missing
        if (!HAS_LIMIT.matcher(cleaned).find()) {
            cleaned = cleaned.replaceFirst(";\\s*$", "") + " LIMIT " + MAX_ROWS;
        }

        return new ValidatedSql(cleaned, true, null);
    }

    private String askAiToFix(String sql, String error) {
        String prompt = """
                下面的 SQL 执行报错，请修复。
                只返回修复后的 SQL，不要解释、不要 markdown。

                原 SQL：
                %s

                错误：
                %s
                """.formatted(sql, error);

        try {
            return openAiService.chat("你是专业的 SQL 工程师，修复有语法错误的 SQL。", prompt);
        } catch (Exception e) {
            log.warn("AI 自纠 SQL 失败: {}", e.getMessage());
            return sql;
        }
    }

    public static class SqlValidationException extends Exception {
        private final String sql;

        public SqlValidationException(String message, String sql) {
            super(message);
            this.sql = sql;
        }

        public String getSql() {
            return sql;
        }
    }

    public record ValidatedSql(String sql, boolean passed, String errorMessage) {
    }
}
